package movie_csv_Exercise;

public enum Category {
    MOVIEID, TITLE, KOREANTITLE, PLOT, RELEASEYEAR, RUNNINGTIME, GRADEID, GRADEINKOREAID,
    POSTER, RELEASEDATEINKOREA, BOXOFFICEWWGROSS, BOXOFFICEUSGROSS, BUDGET, ORIGINALAUTHOR, ORIGINALSOURCE;
}
