package movie;

public enum Category {
    ID, RELEASEYEAR, RUNNINGTIME,BOXOFFICEWWGROSS, BOXOFFICEUSGROOS, BUDGET,
    TITLE, KOREANTITLE, PLOT, POSTER, AUTHOR, ORIGINALSOURCE,
    GRADEID, GRADEKOREANID, RELEASEDATEINKOREA;
}
